#!/usr/bin/env python3
"""
Build assets/fonts/ and css/fonts.css from the Fontsource npm packages.

The page used to pull five families from the Google Fonts CDN on every
visit — a render-blocking request to a third party before a single word
could be painted. The faces are served from our own origin instead, cut
to the subsets the four languages actually use.

Install the packages, then run this from the repo root:

    npm i @fontsource-variable/playfair-display \\
          @fontsource-variable/unbounded \\
          @fontsource-variable/mulish \\
          @fontsource-variable/cairo \\
          @fontsource/amiri \\
          @fontsource/tajawal
    python3 tools/build-fonts.py [--modules path/to/node_modules]

Writes:  assets/fonts/*.woff2, assets/fonts/LICENSE.txt, css/fonts.css
"""

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "assets" / "fonts"
OUT_CSS = ROOT / "css" / "fonts.css"

# Which subsets each family is shipped in. Vietnamese and Hebrew are
# dropped: nothing on the site is set in them, and an unused @font-face
# still costs a line of CSS on every page.
#
#   (package, css family name, kind, subsets, weights/styles)
#
# kind "var" is one file per subset covering the whole weight axis;
# kind "static" is one file per subset per weight.
FAMILIES = [
    {
        "pkg": "@fontsource-variable/playfair-display",
        "family": "Playfair Display Variable",
        "kind": "var",
        "stem": "playfair-display",
        "subsets": ["latin", "latin-ext", "cyrillic"],
        "styles": ["normal", "italic"],
        "weights": "400 900",
    },
    {
        "pkg": "@fontsource-variable/unbounded",
        "family": "Unbounded Variable",
        "kind": "var",
        "stem": "unbounded",
        "subsets": ["latin", "latin-ext", "cyrillic", "cyrillic-ext"],
        "styles": ["normal"],
        "weights": "200 900",
    },
    {
        "pkg": "@fontsource-variable/mulish",
        "family": "Mulish Variable",
        "kind": "var",
        "stem": "mulish",
        "subsets": ["latin", "latin-ext", "cyrillic", "cyrillic-ext"],
        "styles": ["normal", "italic"],
        "weights": "200 1000",
    },
    {
        "pkg": "@fontsource-variable/cairo",
        "family": "Cairo Variable",
        "kind": "var",
        "stem": "cairo",
        "subsets": ["arabic", "latin", "latin-ext"],
        "styles": ["normal"],
        "weights": "200 1000",
    },
    {
        # the ambient Arabic words in the background are set in Amiri on
        # every page, so its Arabic cut ships regardless of language
        "pkg": "@fontsource/amiri",
        "family": "Amiri",
        "kind": "static",
        "stem": "amiri",
        "subsets": ["arabic", "latin"],
        "styles": ["normal"],
        "weights": [400, 700],
    },
    {
        "pkg": "@fontsource/tajawal",
        "family": "Tajawal",
        "kind": "static",
        "stem": "tajawal",
        "subsets": ["arabic", "latin"],
        "styles": ["normal"],
        "weights": [400, 500, 700, 800],
    },
]

HEADER = """/* =============================================================
   Self-hosted webfonts — generated by tools/build-fonts.py
   Do not edit by hand; edit the generator and re-run it.

   Sources: Fontsource (https://fontsource.org), all faces under the
   SIL Open Font License 1.1. See assets/fonts/LICENSE.txt.

   Roles (see css/style.css):
     Playfair Display  display — headlines, the voice of the page
     Unbounded         signage — nav, buttons, eyebrows, figures
     Mulish            body    — every run of text
     Amiri / Cairo / Tajawal   the same three roles in Arabic
============================================================= */
"""


def face(family, style, weight, url, urange):
    return (
        "@font-face{\n"
        f"  font-family:'{family}';\n"
        f"  font-style:{style};\n"
        f"  font-weight:{weight};\n"
        "  font-display:swap;\n"
        f"  src:url('{url}') format('woff2');\n"
        f"  unicode-range:{urange};\n"
        "}\n"
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--modules", default="node_modules",
                    help="path to the node_modules holding the Fontsource packages")
    args = ap.parse_args()
    modules = Path(args.modules).resolve()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("*.woff2"):
        stale.unlink()

    css = [HEADER]
    licences = []
    shipped = 0

    for spec in FAMILIES:
        pkg = modules / spec["pkg"]
        if not pkg.is_dir():
            raise SystemExit(f"missing package {spec['pkg']} under {modules}")
        ranges = json.loads((pkg / "unicode.json").read_text())
        lic = pkg / "LICENSE"
        if lic.is_file():
            licences.append(f"### {spec['family']} ({spec['pkg']})\n\n" + lic.read_text())

        css.append(f"\n/* ---- {spec['family']} ---- */\n")
        for subset in spec["subsets"]:
            urange = ranges.get(subset)
            if not urange:
                raise SystemExit(f"{spec['pkg']}: no unicode range for {subset}")
            for style in spec["styles"]:
                weights = ([spec["weights"]] if spec["kind"] == "var"
                           else spec["weights"])
                for weight in weights:
                    if spec["kind"] == "var":
                        name = f"{spec['stem']}-{subset}-wght-{style}.woff2"
                    else:
                        suffix = "normal" if style == "normal" else "italic"
                        name = f"{spec['stem']}-{subset}-{weight}-{suffix}.woff2"
                    src = pkg / "files" / name
                    if not src.is_file():
                        raise SystemExit(f"missing font file {src}")
                    shutil.copy2(src, OUT_DIR / name)
                    shipped += 1
                    css.append(face(spec["family"], style, weight,
                                    f"/assets/fonts/{name}", urange))

    OUT_CSS.write_text("".join(css), encoding="utf-8")
    (OUT_DIR / "LICENSE.txt").write_text(
        "The webfonts in this directory are redistributed under the SIL Open\n"
        "Font License 1.1. Full text of each family's licence follows.\n\n"
        + "\n\n".join(licences),
        encoding="utf-8",
    )

    total = sum(f.stat().st_size for f in OUT_DIR.glob("*.woff2"))
    print(f"{shipped} faces -> {OUT_DIR.relative_to(ROOT)} ({total/1024:.0f} KB)")
    print(f"stylesheet     -> {OUT_CSS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
